CREATE TABLE IF NOT EXISTS  templates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  hash TEXT NOT NULL UNIQUE,
  creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modification TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  path TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS content (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  hash TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  path TEXT NOT NULL,
  tid INTEGER,
  creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modification TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(tid) REFERENCES templates(id)
);

CREATE TABLE IF NOT EXISTS revisions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  revision TEXT NOT NULL,
  previous TEXT NOT NULL,
  creation TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

